### PR TITLE
fix: ignore tsconfig setting files

### LINKED ISSUE #91: 🐛 BUG: `strict` tsconfig rule causes linting errors in `.astro` files
### What package manager are you using?

yarn

### What operating system are you using?

macOS

### Describe the Bug

When using a `tsconfig.json` file such as :

```
{
   "compilerOptions": {
      "strict": true,
      "alwaysStrict": true
   }
}
```

Visual Studio Code highlights all of the JSX and shows this linting error:

`JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.`

image

In Discord, Matthew2 suspects this might be a bug with the Astro extension.

https://discord.com/channels/830184174198718474/845451724738265138/895704312544653353

### Steps to Reproduce

1. `npm init astro --template minimal` using template <NAME>
2. Open `index.astro` and note the lack of linting warnings.
3. Add the `tsconfig.json` sample above.
4. Close and then reopne `index.astro`.
5. Notice all the linting errors.

### Link to Minimal Reproducible Example (Optional)

https://github.com/justinnoel/astro-jsx-linting-issue

### PR DESCRIPTION
**Pull request by matthewp**
Astro should not be reading the tsconf settings file.  This causes issues  such as `strict: true` causing ts errors like:

`JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.`

RE: https://discord.com/channels/830184174198718474/845451724738265138/895704312544653353

Closes #91.

Personal References:
- Link #T-366
- Closes #T-366

### CODE REVIEW

**Comment by matthewp** [comment]
I'm submitting this, as its been a continued problem where people's tsconfig conflicts with Astro. So simply not using tsconfig in .astro files fixes the problem.

File: packages/language-server/src/plugins/typescript/languageService.ts [hunk 1]
```diff
@@ -174,22 +163,19 @@ async function createLanguageService(tsconfigPath: string, workspaceRoot: string
   }
 }
 
-/**
- * This should only be used when there's no jsconfig/tsconfig at all
- */
 function getDefaultJsConfig(): {
-  compilerOptions: ts.CompilerOptions;
-  include: string[];
+   compilerOptions: ts.CompilerOptions;
```
Comment (jonathantneal) [inline packages/language-server/src/plugins/typescript/languageService.ts:167]: Nit: **3-space has entered the chat** 😂

**Review by jonathantneal — APPROVED** [review]
Excellent!

File: packages/language-server/src/plugins/typescript/languageService.ts (hunk 1 above)
Comment (matthewp) [reply packages/language-server/src/plugins/typescript/languageService.ts:167]: Do we not have formatting set up on CI? I guess we didn't do that here yet.

Comment (matthewp) [reply packages/language-server/src/plugins/typescript/languageService.ts:167]: I ran it locally and there are a *lot* of changes. Probably should submit that as a different PR and set it up with CI like we have in the main repo.
